# Generated by Django 4.1.3 on 2023-01-08 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_productdb_pprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorydb',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='productdb',
            name='Description',
        ),
    ]
